### ISSUE TITLE
Possible Infinite Loop

### ISSUE THREAD

**Issue by AZMCode** [chrisnc/wordletron#1]
While using the solve-wordle command, I've always gotten stuck while calculating the "best next guess". I've manually disabled this part, and it works fine, so there appears to be an inadvertent infinite loop in there. I'll dive deeper into this and perhaps provide some insight tomorrow.

**Comment by chrisnc** [comment]
What version are you using?
Can you give an example of a guess and a clue that causes this?
Generally the best guess calculation should be very fast after the first clue, which is the only time it runs. When I was working on it initially I had it compute the best first guess as well, but this will be the same result every time given the scoring function and word lists, so I made this part separate and let the user specify the starting word in `solve-wordle` and only compute subsequent guesses.

With the current version of the code, though, even computing the first guess happens in a few hundred milliseconds on my machine (M1 Pro).

**Comment by AZMCode** [comment]
I was using a Galaxy J5 phone using Termux and Wordletron 0.1.7, but I appear to be unable to reproduce the issue anymore. Must've been some unexpected incident with my device. I apologize for the inconvenience.
Closing.

**Comment by chrisnc** [comment]
Interesting. So, that processor is quite a bit slower than what I've run this on, and the guess compute function will use all available cores. By geekbench 5 multicore score, the M1 Pro is about 30x faster than your phone, so I'd expect some guess computations to take several seconds, and substantially longer than that if you're not running a `--release` build. The other thing is that some initial guesses and clues will eliminate comparatively few words, and so the guess calculation that runs for the second guess is solving a problem almost as large as the first guess calculation. The complexity of the function is quadratic: O(num_answers * num_guesses). Do you remember how long you let it run with no apparent progress?

**Comment by AZMCode** [comment]
A minute or two

**Comment by chrisnc** [comment]
Were you using a `--release` build?

**Comment by AZMCode** [comment]
I think I was

**Comment by chrisnc** [comment]
That would be the difference, most likely. On a debug build my laptop takes 12.3s to compute the best first guess, which on your phone I estimate would take roughly 6 minutes (12.3s * 30 = 369s). On a release build my machine takes under half a second and I would expect your phone to take ~15 seconds.
